services:
  finapp:
    build: .
    container_name: finapp
    ports:
      - "5000:5000"  # This exposes the app on port 5000 of your Docker host
    volumes:
      - ./data:/app/data          # Persist SQLite database
      - ./logs:/app/logs          # Persist application logs (optional)
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      # SQLite connection string (if you need to customize the database path)
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/investmenttracker.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - finapp-network

networks:
  finapp-network:
    driver: bridge

# Optional: Add a volume for explicit data management
volumes:
  finapp-data:
    driver: local
