// <auto-generated />
using System;
using InvestmentTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvestmentTracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250908205325_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestmentTracker.Models.CategoryBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EndMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<int>("ExpenseCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("StartMonth")
                        .HasColumnType("integer");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategoryId", "StartYear", "StartMonth");

                    b.HasIndex("ExpenseCategoryId", "StartYear", "StartMonth", "EndYear", "EndMonth")
                        .HasDatabaseName("IX_CategoryBudgets_TemporalLookup");

                    b.HasIndex("StartYear", "StartMonth", "EndYear", "EndMonth", "ExpenseCategoryId", "Amount")
                        .HasDatabaseName("IX_CategoryBudgets_CoveringQuery");

                    b.ToTable("CategoryBudgets");
                });

            modelBuilder.Entity("InvestmentTracker.Models.ContributionSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<int>("InvestmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentId", "StartDate");

                    b.ToTable("ContributionSchedules");
                });

            modelBuilder.Entity("InvestmentTracker.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("InvestmentTracker.Models.ExpenseSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EndMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<int>("RegularExpenseId")
                        .HasColumnType("integer");

                    b.Property<int>("StartMonth")
                        .HasColumnType("integer");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegularExpenseId", "StartYear", "StartMonth");

                    b.HasIndex("StartYear", "StartMonth", "EndYear", "EndMonth")
                        .HasDatabaseName("IX_ExpenseSchedules_TemporalLookup");

                    b.HasIndex("StartYear", "StartMonth", "EndYear", "EndMonth", "RegularExpenseId", "Amount", "Frequency")
                        .HasDatabaseName("IX_ExpenseSchedules_CoveringQuery");

                    b.ToTable("ExpenseSchedules");
                });

            modelBuilder.Entity("InvestmentTracker.Models.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("FamilyMember");
                });

            modelBuilder.Entity("InvestmentTracker.Models.IncomeSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IncomeSources");
                });

            modelBuilder.Entity("InvestmentTracker.Models.Investment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<decimal>("ChargeAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provider")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("InvestmentTracker.Models.InvestmentValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AsOf")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvestmentId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentId", "AsOf")
                        .IsUnique();

                    b.ToTable("InvestmentValues");
                });

            modelBuilder.Entity("InvestmentTracker.Models.IrregularExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExpenseCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("integer");

                    b.Property<int?>("FamilyMemberId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_IrregularExpenses_Date");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("FamilyMemberId");

                    b.HasIndex("Date", "ExpenseCategoryId", "Amount")
                        .HasDatabaseName("IX_IrregularExpenses_DateCategoryAmount");

                    b.ToTable("IrregularExpenses");
                });

            modelBuilder.Entity("InvestmentTracker.Models.MonthlyIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("IncomeSourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Month")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IncomeSourceId", "Month")
                        .IsUnique();

                    b.ToTable("MonthlyIncomes");
                });

            modelBuilder.Entity("InvestmentTracker.Models.OneTimeContribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvestmentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentId", "Date");

                    b.ToTable("OneTimeContributions");
                });

            modelBuilder.Entity("InvestmentTracker.Models.OneTimeIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IncomeSourceId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("IncomeSourceId");

                    b.ToTable("OneTimeIncomes");
                });

            modelBuilder.Entity("InvestmentTracker.Models.RegularExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("ExpenseCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("integer");

                    b.Property<int?>("FamilyMemberId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("FamilyMemberId");

                    b.ToTable("RegularExpenses");
                });

            modelBuilder.Entity("InvestmentTracker.Models.CategoryBudget", b =>
                {
                    b.HasOne("InvestmentTracker.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");
                });

            modelBuilder.Entity("InvestmentTracker.Models.ContributionSchedule", b =>
                {
                    b.HasOne("InvestmentTracker.Models.Investment", "Investment")
                        .WithMany("Schedules")
                        .HasForeignKey("InvestmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investment");
                });

            modelBuilder.Entity("InvestmentTracker.Models.ExpenseSchedule", b =>
                {
                    b.HasOne("InvestmentTracker.Models.RegularExpense", "RegularExpense")
                        .WithMany("Schedules")
                        .HasForeignKey("RegularExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegularExpense");
                });

            modelBuilder.Entity("InvestmentTracker.Models.InvestmentValue", b =>
                {
                    b.HasOne("InvestmentTracker.Models.Investment", "Investment")
                        .WithMany("Values")
                        .HasForeignKey("InvestmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investment");
                });

            modelBuilder.Entity("InvestmentTracker.Models.IrregularExpense", b =>
                {
                    b.HasOne("InvestmentTracker.Models.ExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryId");

                    b.HasOne("InvestmentTracker.Models.FamilyMember", "FamilyMember")
                        .WithMany()
                        .HasForeignKey("FamilyMemberId");

                    b.Navigation("Category");

                    b.Navigation("FamilyMember");
                });

            modelBuilder.Entity("InvestmentTracker.Models.MonthlyIncome", b =>
                {
                    b.HasOne("InvestmentTracker.Models.IncomeSource", "IncomeSource")
                        .WithMany()
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("InvestmentTracker.Models.OneTimeContribution", b =>
                {
                    b.HasOne("InvestmentTracker.Models.Investment", "Investment")
                        .WithMany("OneTimeContributions")
                        .HasForeignKey("InvestmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investment");
                });

            modelBuilder.Entity("InvestmentTracker.Models.OneTimeIncome", b =>
                {
                    b.HasOne("InvestmentTracker.Models.IncomeSource", "IncomeSource")
                        .WithMany()
                        .HasForeignKey("IncomeSourceId");

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("InvestmentTracker.Models.RegularExpense", b =>
                {
                    b.HasOne("InvestmentTracker.Models.ExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryId");

                    b.HasOne("InvestmentTracker.Models.FamilyMember", "FamilyMember")
                        .WithMany()
                        .HasForeignKey("FamilyMemberId");

                    b.Navigation("Category");

                    b.Navigation("FamilyMember");
                });

            modelBuilder.Entity("InvestmentTracker.Models.Investment", b =>
                {
                    b.Navigation("OneTimeContributions");

                    b.Navigation("Schedules");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("InvestmentTracker.Models.RegularExpense", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
